/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAL.ZeroMqRequest;
import Model.Pessoa;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class TelaCoordenador extends javax.swing.JFrame {

    public ZeroMqRequest requester;
    public ArrayList<Pessoa> alunos = new ArrayList();
    public ArrayList<Pessoa> professores = new ArrayList();;
    
    public TelaCoordenador() {
        initComponents();
        initLists();
        initCombos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRevisao = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCod = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEtapa = new javax.swing.JComboBox<>();
        btDefCrono = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbAluno = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cbOrientador = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtOrientador = new javax.swing.JTextField();
        btAtribuir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbBanca1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtBanca1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbBanca2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtBanca2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/android-chrome-192x192.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cronograma"));

        jLabel5.setText("Prazo de Entrega:");

        txtEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtEntrega.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("Prazo de Revisão:");

        txtRevisao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtRevisao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("Código de Etapa:");

        txtCod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel3.setText("Nome da Etapa:");

        cbEtapa.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cbEtapa.setMaximumRowCount(5);
        cbEtapa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proposta TC", "Reelaboracao de Proposta", "TC", "Reelaboracao de TC", "Outros" }));

        btDefCrono.setText("Definir cronograma");
        btDefCrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDefCronoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRevisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEtapa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btDefCrono, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btDefCrono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Aluno:");

        txtAluno.setEditable(false);
        txtAluno.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        txtAluno.setText("santos da silva");
        txtAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlunoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Matrícula:");

        cbAluno.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        cbAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlunoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Orientador:");

        cbOrientador.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        cbOrientador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOrientadorItemStateChanged(evt);
            }
        });
        cbOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrientadorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nome Prof.");

        txtOrientador.setEditable(false);
        txtOrientador.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        txtOrientador.setText("santos da silva");
        txtOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrientadorActionPerformed(evt);
            }
        });

        btAtribuir.setText("Atribuir");
        btAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtribuirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Banca:");

        cbBanca1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        cbBanca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBanca1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Nome Prof.");

        txtBanca1.setEditable(false);
        txtBanca1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        txtBanca1.setText("santos da silva");
        txtBanca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanca1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Banca:");

        cbBanca2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        cbBanca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBanca2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Noto Sans", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Nome Prof.");

        txtBanca2.setEditable(false);
        txtBanca2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        txtBanca2.setText("santos da silva");
        txtBanca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanca2ActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtOrientador, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                    .addComponent(cbOrientador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBanca2)
                                    .addComponent(cbBanca2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBanca1)
                                        .addComponent(cbBanca1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtribuir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbBanca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtBanca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbBanca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtBanca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btAtribuir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDefCronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDefCronoActionPerformed
        if(txtEntrega.getText().isBlank() || txtRevisao.getText().isBlank() || txtCod.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Campos não preenchidos adequadamente","Erro no Cronograma", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date dataRevisao = new Date();
        Date dataEntrega = new Date();
        
        try{
            dataRevisao = dateFormat.parse(txtRevisao.getText());
            dataEntrega = dateFormat.parse(txtEntrega.getText());
        }catch(Exception ex){
            System.out.println(ex);
        }
        
        
        String req = "defEtapa;"+txtCod.getText()+";"+cbEtapa.getSelectedItem().toString()+";"+dataEntrega.getTime()+";"+dataRevisao.getTime();
        
        requester.sendRequest(req);
        
        String reply = requester.receiveReply();
        
        System.out.println(reply);
        
        String[] replySplit = reply.split(";");
        
        switch(replySplit[0]){
            case "falha":
                JOptionPane.showMessageDialog(null, replySplit[1],"Erro na criação do cronograma", JOptionPane.ERROR_MESSAGE);
                break;
                
            case "sucesso":
                JOptionPane.showMessageDialog(null, "Cronograma criado","Sucesso", JOptionPane.INFORMATION_MESSAGE);
                break;
                
            default:
                JOptionPane.showMessageDialog(null, "Resposta não identificada","alerta", JOptionPane.ERROR_MESSAGE);
                break;
        }
        
    }//GEN-LAST:event_btDefCronoActionPerformed

    private void txtAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlunoActionPerformed

    private void txtOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrientadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrientadorActionPerformed

    private void txtBanca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanca1ActionPerformed

    private void txtBanca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanca2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanca2ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void cbOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrientadorActionPerformed
        txtOrientador.setText(professores.get(cbOrientador.getSelectedIndex()).nome);
    }//GEN-LAST:event_cbOrientadorActionPerformed

    private void cbBanca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBanca1ActionPerformed
        txtBanca1.setText(professores.get(cbBanca1.getSelectedIndex()).nome);
    }//GEN-LAST:event_cbBanca1ActionPerformed

    private void cbAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunoActionPerformed
        txtAluno.setText(alunos.get(cbAluno.getSelectedIndex()).nome);
    }//GEN-LAST:event_cbAlunoActionPerformed

    private void cbBanca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBanca2ActionPerformed
        txtBanca2.setText(professores.get(cbBanca2.getSelectedIndex()).nome);
    }//GEN-LAST:event_cbBanca2ActionPerformed

    private void cbOrientadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOrientadorItemStateChanged
        Pessoa p = (Pessoa) cbOrientador.getSelectedItem();
        txtOrientador.setText("teste");
    }//GEN-LAST:event_cbOrientadorItemStateChanged

    private void btAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtribuirActionPerformed
        Pessoa aluno,orientador,banca1,banca2;
        aluno = (Pessoa) cbAluno.getSelectedItem();
        orientador = (Pessoa) cbOrientador.getSelectedItem();
        banca1 = (Pessoa) cbBanca1.getSelectedItem();
        banca2 = (Pessoa) cbBanca2.getSelectedItem();
        if(orientador.matricula.equals(banca1.matricula) || orientador.matricula.equals(banca2.matricula) || banca1.matricula.equals(banca2.matricula)){
            JOptionPane.showMessageDialog(null, "Um professor não pode ser atribuido duas vezes a mesma banca","Erro ao criar banca", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String req = "defBanca;"+aluno.matricula+";"+orientador.matricula+";"+banca1.matricula+";"+banca2.matricula;
        
        requester.sendRequest(req);
        
        String reply = requester.receiveReply();
        
        System.out.println(reply);
        
        String[] replySplit = reply.split(";");
        
        switch(replySplit[0]){
            case "falha":
                JOptionPane.showMessageDialog(null, replySplit[1],"Erro no cadastro", JOptionPane.ERROR_MESSAGE);
                break;
            case "sucesso":
                JOptionPane.showMessageDialog(null, replySplit[1],"Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Resposta não identificada","alerta", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btAtribuirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtribuir;
    private javax.swing.JButton btDefCrono;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<Object> cbAluno;
    private javax.swing.JComboBox<Object> cbBanca1;
    private javax.swing.JComboBox<Object> cbBanca2;
    private javax.swing.JComboBox<String> cbEtapa;
    private javax.swing.JComboBox<Object> cbOrientador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextField txtBanca1;
    private javax.swing.JTextField txtBanca2;
    private javax.swing.JFormattedTextField txtCod;
    private javax.swing.JFormattedTextField txtEntrega;
    private javax.swing.JTextField txtOrientador;
    private javax.swing.JFormattedTextField txtRevisao;
    // End of variables declaration//GEN-END:variables

    private void initLists(){
        requester = new ZeroMqRequest();
        
        String req = "SearchPessoa;1";
        requester.sendRequest(req);
        String reply = requester.receiveReply();
        
        String[] splited = reply.split(";");
        for (int i = 1; i < splited.length; i++) {            
            String[] pessoaString = splited[i].split(":");
            for (int j = 0; j < pessoaString.length; j++) {
                Pessoa p = new Pessoa();
                String[] pessoaFinal = pessoaString[j].split("\\|");
                p.matricula = pessoaFinal[0];
                p.nome = pessoaFinal[1];
                alunos.add(p);
            }
        }
        
         req = "SearchPessoa;2";
        requester.sendRequest(req);
         reply = requester.receiveReply();
        
        splited = reply.split(";");
        for (int i = 1; i < splited.length; i++) {
            
            
            String[] pessoaString = splited[i].split(":");
            for (int j = 0; j < pessoaString.length; j++) {
                Pessoa p = new Pessoa();
                String[] pessoaFinal = pessoaString[j].split("\\|");
                p.matricula = pessoaFinal[0];
                p.nome = pessoaFinal[1];
                professores.add(p);
            }
        }
        System.out.println("fim");
    }
    
    private void initCombos(){
        for (int i = 0; i < alunos.size(); i++) {
            cbAluno.addItem(alunos.get(i));
        }
        
        for (int i = 0; i < professores.size(); i++) {
            cbBanca1.addItem(professores.get(i));
            cbBanca2.addItem(professores.get(i));
            cbOrientador.addItem(professores.get(i));
        }
    }
}
