/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAL.ZeroMqRequest;
import Model.Etapa;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class TelaCriarTrab extends javax.swing.JFrame{
    ArrayList<Etapa> etapas = new ArrayList();
    String aluno;
    ZeroMqRequest requester = new ZeroMqRequest();
    TelaAluno2 t;
    
    public TelaCriarTrab(String matricula, TelaAluno2 t) {
        this.t = t;
        this.t.setVisible(false);
        aluno = matricula;
        initComponents();
        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        String req = "SearchEtapa;";
        
        requester.sendRequest(req);
        
        String reply = requester.receiveReply();
        
        System.out.println(reply);
        
        String[] replySplit = reply.split(";");
        
        switch(replySplit[0]){
            case "falha":
                JOptionPane.showMessageDialog(null, replySplit[1],"Erro na criação do cronograma", JOptionPane.ERROR_MESSAGE);
                break;
                
            case "sucesso":
                initLists(reply);
                initCombos();
                break;
                
            default:
                JOptionPane.showMessageDialog(null, "Resposta não identificada","alerta", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbEtapas = new javax.swing.JComboBox<>();
        txtPrazo = new javax.swing.JTextField();
        btCriar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Titulo do Trabalho");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Etapa");

        cbEtapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEtapasActionPerformed(evt);
            }
        });

        txtPrazo.setEditable(false);

        btCriar.setText("Criar");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel2))
                            .addComponent(txtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCriar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btFechar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbEtapas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbEtapas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCriar)
                    .addComponent(btFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
        this.t.setVisible(true);
    }//GEN-LAST:event_btFecharActionPerformed

    private void cbEtapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEtapasActionPerformed
        Etapa e = (Etapa) cbEtapas.getSelectedItem();
        txtPrazo.setText("E: "+e.PrazoEntrega.toString()+"  - R: "+e.PrazoRevisao.toString());
    }//GEN-LAST:event_cbEtapasActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        Etapa e = (Etapa) cbEtapas.getSelectedItem();
        String req = "defTc;"+aluno+";"+txtTitulo.getText()+";"+e.Codigo;
        
        requester.sendRequest(req);
        
        String reply = requester.receiveReply();
        
        System.out.println(reply);
        
        String[] replySplit = reply.split(";");
        
        switch(replySplit[0]){
            case "falha":
                JOptionPane.showMessageDialog(null, replySplit[1],"Erro na criação do trabalho", JOptionPane.ERROR_MESSAGE);
                break;
                
            case "sucesso":
                JOptionPane.showMessageDialog(null, "Trabalho criado","Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                this.t.setVisible(true);
                break;
                
            default:
                JOptionPane.showMessageDialog(null, "Resposta não identificada","alerta", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_btCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btFechar;
    private javax.swing.JComboBox<Object> cbEtapas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPrazo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
private void initLists(String reply){
        String req = "SearchPessoa;1";
        
        String[] splited = reply.split(";");
        for (int i = 1; i < splited.length; i++) {            
            String[] etapaString = splited[i].split("\\*");
            for (int j = 0; j < etapaString.length; j++) {
                Etapa e = new Etapa();
                String[] etapaFinal = etapaString[j].split("\\|");
                e.Codigo = Integer.valueOf(etapaFinal[0]);
                e.DescEtapa = etapaFinal[1];
                e.PrazoEntrega = new Date(Long.valueOf(etapaFinal[2]));
                e.PrazoRevisao = new Date(Long.valueOf(etapaFinal[3]));

                etapas.add(e);
            }
        }
        System.out.println("fim");
    }
    
    private void initCombos(){
        cbEtapas.removeAllItems();
        for (int i = 0; i < etapas.size(); i++) {
            cbEtapas.addItem(etapas.get(i));
        }
    }

}
